### ISSUE TITLE
strptime() exception when WILD_CARD_DAG_KEY is not set

### ISSUE THREAD

**Issue by rousso** [OP-TED/ted-rdf-conversion-pipeline#400]
This issue prevents fetching some notices from TED. Apparently when the WILD_CARD_DAG_KEY parameter is not set, the strptime() method throws an exception which stops processing. We think that we should be able to handle this issue gracefully and avoid terminating the fetch. What causes the WILD_CARD_DAG_KEY to be empty?

Stack trace below.
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/notice_fetch_by_date_workflow.py", line 61, in validate_fetched_notices
    publication_date = datetime.strptime(get_dag_param(key=WILD_CARD_DAG_KEY), "%Y%m%d*")
TypeError: strptime() argument 1 must be str, not None
```

**Comment by CaptainOfHacks** [comment]
This bug was fixed, this bugfix will be included in new release.
